### ISSUE TITLE
I can't install urlparse4 with pip

### ISSUE THREAD

**Issue by malloxpb** [commonsearch/urlparse4#13]
When I ran **pip install urlparse4**, I got this error:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5b/14v9crsn0x7b9v58170lv8jc0000gn/T/pip-install-m3mb197e/urlparse4/setup.py", line 46
        print "urlparse4/gurl.cpp not found and Cython failed to run to recreate it. Please install/upgrade Cython and try again."
                                                                                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5b/14v9crsn0x7b9v58170lv8jc0000gn/T/pip-install-m3mb197e/urlparse4/
```

Therefore, can you take a look at it? Thank you!

**Comment by lopuhin** [comment]
I think it fails to install under python 3 due to https://github.com/commonsearch/urlparse4/issues/5
