### ISSUE TITLE
Test on PyPy

### ISSUE THREAD

**Issue by sylvinus** [commonsearch/urlparse4#4]
We could use testing code from https://github.com/commonsearch/gumbocy

**Comment by ev1351** [comment]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eglzy0ga/urlparse4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eglzy0ga/urlparse4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jwjpxc_0
         cwd: /tmp/pip-install-eglzy0ga/urlparse4/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eglzy0ga/urlparse4/setup.py", line 46
        print "urlparse4/gurl.cpp not found and Cython failed to run to recreate it. Please install/upgrade Cython and try again."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("urlparse4/gurl.cpp not found and Cython failed to run to recreate it. Please install/upgrade Cython and try again.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

how to solve this
